---
- name: Configure WireGuard
  hosts: vpn_server
  gather_facts: no
  become: yes
  tasks:
    - name: Install WireGuard tools
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - wireguard-tools
        - net-tools

    - name: Create WireGuard config directory
      file:
        path: /etc/wireguard
        state: directory

    - name: Check if private key exists
      stat:
        path: /etc/wireguard/privatekey
      register: privatekey_file

    - name: Check if public key exists
      stat:
        path: /etc/wireguard/publickey
      register: publickey_file

    - name: Generate WireGuard keys
      shell: |
        wg genkey | tee /etc/wireguard/privatekey
      when: not privatekey_file.stat.exists

    - name: Generate WireGuard public key
      shell: |
        cat /etc/wireguard/privatekey | wg pubkey | tee /etc/wireguard/publickey
      when: not publickey_file.stat.exists

    - name: Get private key
      slurp:
        src: /etc/wireguard/privatekey
      register: privatekey

    - name: Get public key
      slurp:
        src: /etc/wireguard/publickey
      register: publickey

    - name: Create WireGuard server config
      template:
        src: templates/server.wg0.conf.j2
        dest: /etc/wireguard/wg0.conf
      vars:
        private_key: "{{ privatekey.content | b64decode | regex_replace('\n$', '') }}"

    - name: Enable ip forwarding between interfaces
      shell: |
        sysctl -w net.ipv4.ip_forward=1; sysctl -p

    - name: Check if wg0 interface exists
      shell: |
        ip link show dev wg0
      ignore_errors: yes
      register: wg0_interface

    - name: Bring interface up if not enabled
      shell: |
        wg-quick up wg0
      when: wg0_interface.rc != 0

    - name: Update configs if already enabled
      shell: |
        temp=`mktemp`
        wg-quick strip wg0 > $temp
        wg syncconf wg0 $temp
      when: wg0_interface.rc == 0

    - name: Enable VPN on boot
      shell: |
        systemctl enable wg-quick@wg0

    - name: Display publickey
      debug:
        msg: "{{ publickey.content | b64decode | regex_replace('\n$', '') }}"
