# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "sos-rs-freetier-tfstate"
    dynamodb_table = "sos-rs-freetier-tfstate-locktable"
    encrypt        = true
    key            = "./terraform.tfstate"
    region         = "sa-east-1"
  }
}
