# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = "sa-east-1"
  allowed_account_ids = [923013710130] 
  default_tags {
    tags = {
      Project = "sos-rs"
      Environment = "freetier"
      Managed-By = "Terraform"
    } 
  }
}
