---
- name: Configure WireGuard
  hosts: backend_server
  gather_facts: no
  become: yes
  vars:
    gh_actions_repo: https://github.com/ppastorf/sos-rs-backend
    gh_actions_token: AGBWQIYXYM6X377CXC4XUT3GKM3IQ
  tasks:
    - name: Create actions-runner directory
      file:
        path: ~/actions-runner
        state: directory

    - name: Download GitHub Actions runner package
      get_url:
        url: "https://github.com/actions/runner/releases/download/v2.316.1/actions-runner-linux-x64-2.316.1.tar.gz"
        dest: "~/actions-runner/actions-runner-linux-x64-2.316.1.tar.gz"

    - name: Extract the installer
      shell: |
        tar xzf ~/actions-runner/actions-runner-linux-x64-2.316.1.tar.gz -C ~/actions-runner/

    - name: Configure the runner
      shell:
        cmd: |
          ./config.sh --url {{ gh_actions_repo }} --token {{ gh_actions_token }}        
        chdir: ~/actions-runner

    - name: Run runner
      shell:
        cmd: |
          ./run.sh
        chdir: ~/actions-runner
